<?php
    session_start();
    ?>
<!DOCTYPE html>
<html>
    <head>
        <title>Hope Hospital</title>
    </head>
    <body>
        <table border="1" align="center" width="650px">
            <tr>
                <td>
                   <h1>Hope Hospital</h1> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; 
                   <a href= "admin_dashboard.php">  Home </a> | <a href="notification.php"> Notification </a> | <a href="logout.php">logout</a>
                </td>
                <tr>
                    <td>
                        <center> 
                            <h4>&lt;&lt;&lt;<em>Salary</em>&gt;&gt;&gt;</h4>
                            <table>
                                <tr>
                                    <th><u>Sr</u></th>
                                    <th><u>Position</u></th>
                                    <th><u>Name</u></th>
                                    <th><u>ID</u></th>
                                    <th><u>Joining Date</u></th>
                                    <th><u>Salary</u></th>
                                </tr>
                                <tr>
                                    <td>01</td>
                                    <td>Doctor</td>
                                    <td>Rhyme</td>
                                    <td>1023-45</td>
                                    <td>23-09-2008</td>
                                    <td>2,28,000</td>
                                <tr>
                                    <td>02</td>
                                    <td>Doctor</td>
                                    <td>Susmita</td>
                                    <td>1109-88</td>
                                    <td>15-04-2015</td>
                                    <td>1,50,000</td>
                                    </tr>
                                </tr>
                                <tr>
                                    <td>03</td>
                                    <td>Doctor</td>
                                    <td>Lily</td>
                                    <td>2107-49</td>
                                    <td>09-12-2020</td>
                                    <td>1,00,000</td>
                                </tr>
                                <tr>
                                    <td>04</td>
                                    <td>Doctor</td>
                                    <td>Abel</td>
                                    <td>7307-41</td>
                                    <td>03-02-2014</td>
                                    <td>1,75,000</td>
                                </tr>
                                <tr>
                                    <td>05</td>
                                    <td>Employee</td>
                                    <td>Raven</td>
                                    <td>80-46-88</td>
                                    <td>11-08-2004</td>
                                    <td>45,000</td>
                                </tr>
                                <tr>
                                    <td>06</td>
                                    <td>Employee</td>
                                    <td>Selena</td>
                                    <td>49-87-21</td>
                                    <td>15-06-2013</td>
                                    <td>42,000</td>
                                </tr>
                                <tr>
                                    <td>07</td>
                                    <td>Employee</td>
                                    <td>Henry</td>
                                    <td>28-27-49</td>
                                    <td>29-12-2009</td>
                                    <td>40,000</td>
                                </tr>
                                <tr>
                                    <td>08</td>
                                    <td>Employee</td>
                                    <td>Jolene</td>
                                    <td>61-82-46</td>
                                    <td>13-07-2008</td>
                                    <td>38,000</td>
                                </tr>
                                <tr>
                                    <td>09</td>
                                    <td>Accountant</td>
                                    <td>Edward</td>
                                    <td>08-5940</td>
                                    <td>09-06-2001</td>
                                    <td>80,000</td>
                                </tr>
                                <tr>
                                    <td>10</td>
                                    <td>Accountant</td>
                                    <td>Cory</td>
                                    <td>79-0741</td>
                                    <td>18-11-2017</td>
                                    <td>75,000</td>
                                </tr>
                                <tr>
                                    <td>11</td>
                                    <td>Admin</td>
                                    <td>Sumaiya</td>
                                    <td>72-0881</td>
                                    <td>11-11-1997</td>
                                    <td>92,000</td>
                                </tr>
                                <tr>
                                    <td>12</td>
                                    <td>Admin</td>
                                    <td>Miley</td>
                                    <td>25-0741</td>
                                    <td>17-07-2017</td>
                                    <td>88,000</td>
                                </tr>
                                </table>
                                </center>  
                                <br>  
                    </td>
                </tr>
                <tr>
                    <td>
                        <center>
                            Copyright &copy; 1958
                        </center>
                    </td>
                </tr>
            </tr>
        </table>
    </body>
</html>